language: dart

sudo: false

dart:
  - dev
  - stable

dart_task:
  - test: --platform vm

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.pub-cache

before_script:
  - bin/check_formatting

script:
  - bin/fetch-configlet
  - bin/configlet lint .
  - pub run test
